dist: xenial
language: generic
sudo: false
cache:
  directories:
  - $HOME/.stack
  - $HOME/.ghc
  - $HOME/.cabal

addons:
  apt:
    packages:
    - libgmp-dev

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal --install-ghc test --only-dependencies
- stack install hlint

script:
- hlint src
- stack --no-terminal test

after_script:
- travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.3.0/shc-linux-x64-$GHCVER.tar.bz2 | tar -xj
- ./shc faber faber-test
